export enum FlowerMotifEnum {
    NONE = "NONE",
    OMBRE = "OMBRE",
    BORD = "BORD",
    TACHETE = "TACHETE",
    ALTERNATIF = "ALTERNATIF",
    RAYE = "RAYE",
    FRAGMENTE = "FRAGMENTE",
    ANNEAU = "ANNEAU",
    CONFETTI = "CONFETTI",
    GEL = "GEL",
    FUSION = "FUSION",
    CRISTAL = "CRISTAL",
    COSMIQUE = "COSMIQUE",
    IRISE = "IRISE",
    LUEUR = "LUEUR",
    PAILLETTES = "PAILLETTES",
    RAYON_DE_SOLEIL = "RAYON_DE_SOLEIL"
}